name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Dependencies
        run: npm Install

      # Build:
      - name: Build Application 
        run: npm run build
      
      # Test:
      - name: Run Tests
        run: npm test
      
      # Deploy:
      - name: Deployment Message
        run: echo "Application is ready to deploy"